



class IndicadoresExplicacao:
    #Metodo construtor para iniciar os atributos de minha classe
    def __init__(self):
        self.pl = ...
        self.psr = ...
        self.p_vp = ...
        self.dy = ...
        self.margem_liquida = ...
        self.margem_ebit = ...
        self.roe = ...
        self.marge_bruta = ...
        self.p_ebit = ...
        self.roa = ...